### ISSUE TITLE
Memory Profiling

### ISSUE THREAD

**Issue by smudge202** [Steve-Fenton/TfsCruiser#4]
I've noticed that the displays here semi-regularly crash the browser. Probably the best place to start would be to grab some crash logs from our IT guys (//cc @shaundodimead ) but from my experience this is most often caused by memory leaks.

I'll raise an IT ticket internally to see if we can get some browser crash dumps but I'd bet a can of relentless that this is leaking. I'll try to get the full specs/details but at a glance this is a Raspberry Pi 2 device running Chromium in Ubuntu.

**Comment by smudge202** [comment]
Internal tracking ID for getting the logs and such is `INC0012096`.

**Comment by Steve-Fenton** [comment]
Is the problem with the information board, out with the "rotisserie"? I can think of a couple of things off the to of my head that might cause a problem in the rotisserie.

**Comment by smudge202** [comment]
_"rotisserie"_?

I haven't looked properly, but the issue is likely to be that we cycle through a series of urls, each of which loads it's own js. Replacing html content with different content will work correctly with regards to DOM and CSS, but any js objects pushed to a global scope by each of the pages will remain there indefinitely. 

Cruiser can't manage or predict how each page is going to mess with js, but it may be able to take steps to try and reduce memory leakage by those pages (for example, snapshot and compare when a cycle completes in order to try and `delete` properties on global added by the pages)?

_NB: My understanding of TfsCruiser is very limited, I've barely glanced at the code. My understanding of JS mechanisms is quite possibly worse_. :smile: 

EDIT - to reproduce:

Because page content can't be predicted, what would happen if TfsCruiser was set to rotate through a series of pages that each assign a large array to a random global property? I suspect we'd see a memory leak and eventual crashing, which would not _necessarily_ be the _fault_ of the page's author who did not intend for their page to be cycled this way.

**Comment by Steve-Fenton** [comment]
Ha - no worries.

The rotisserie is the page that cycles through a bunch of web pages and that sounds like what you are having a problem with. I'll take a look at how the pages are disposed of once they are replaced to make sure their resources are released.

**Comment by smudge202** [comment]
If all of my above assumptions aren't a complete mess of misconceptions, I believe one way (not necessarily the best) to help reduce the issue would be to snapshot the global properties (by name) when the _rotisserie_ finishes loading (before page content is loaded). Between content updates, compare current global (usually `window` for a site?) to snapshotted, and `delete window.foo` for anything that shouldn't be there.

The above is probably a seriously bad idea for a great number of reasons, but I don't know any such reasons so makes total sense to me. :smile:

**Comment by smudge202** [comment]
If the above doesn't resolve the issue or proves to be too complicated, in previous systems I've written that behave this way we made the bootstrapper much less intelligent. It was responsible for displaying the content of a single page for a given amount of time before redirecting itself back to the server which would do the same for the next page in the cycle (i.e. much more controlled server side than client as compared to current process).

This allows content pages to handle memory like they would do through normal page lifespans.

**Comment by Steve-Fenton** [comment]
The problem on low-spec devices is most likely caused by a couple of contributing factors.

The first is that the Page object holds the iframe with the web page, whether it is the currently displayed item or not...

```
        var Page = (function () {
            var publicProperties = function (url, duration) {
                this.duration = duration || (30 * 1000);
                this.url = url;
                this.displayElement = null;
            }

            publicProperties.prototype.getDisplayElement = function () {
                if (this.displayElement == null) {
                    this.displayElement = document.createElement('iframe');
                    this.displayElement.id = this.id;
                    this.displayElement.src = this.url;
                }

                return this.displayElement;
            };

            return publicProperties;
        }());
```

The second is the number of pages you add to the collection.

I will change the page object so it doesn't hold the iframe element, so we only need two web pages in memory at once (the currently displayed page, and the page being pre-loaded).

**Comment by smudge202** [comment]
Be interesting to see if that helps. Getting a Pi for Christmas so worst case I'll do some hardcore profiling over the holidays. :wink:

**Comment by Steve-Fenton** [comment]
I have a cut down version for you to try out (piviewer.html) if you still have trouble, I may need some additional information on the number of pages and the kind of content they have. It would also be good to hear about any information you can collect when your Pi arrives :)

**Comment by smudge202** [comment]
No problem, will give it a crack when we get the chance.
